on: push
name: Upload to CPanel
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SRV }}
        username: ${{ secrets.FTP_UNAME }}
        password: ${{ secrets.FTP_PSW }}
        server-dir: public_html/
        exclude: .git*
          - .git*/**
          - **/.git*/**
          - nbprojects/**
          - szallas/config/*.php
          
